# Generated by Django 5.2.4 on 2025-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_image_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=0, help_text='Enter proficiency as a percentage (0-100)'),
        ),
    ]
